proyecto_1/apps/contact/urls.py
from django.urls import path
from .views import CreateContact, ListViewContact,Contact,UpdateContact,DeleteViewContact

app_name="contact"

urlpatterns = [
    path('',ListViewContact.as_view(),name="contacts"),
    path('create/',CreateContact.as_view(),name='create-contact' ),
    path('update/<int:pk>/',UpdateContact.as_view(), name='update-contact' ),
    path('contact/<int:pk>/',Contact.as_view(),name="detail-contact" ),
    path('delete/<int:pk>/',DeleteViewContact.as_view(),name="delete-contact" ),
   # path('/contacts/delete', ),
    
]

proyecto_1/apps/core/urls.py
from django.urls import path, include
from .views import HomeViews 

app_name="core"

urlpatterns = [
    path('', HomeViews.as_view(),name='home-core' ),
    
    
    #path('home/', .as_view(),name='' )
]

proyecto_1/apps/issue/urls.py
from django.urls import path 
from .views import IssueCreateView, CategoriesView , typesView,IssueDetailView, IssueListView ,IssueUpdateView, IssueDeleteView

app_name="issue"

urlpatterns = [
    path('create/', IssueCreateView.as_view(), name='create_issue'),
    path('detail/<int:pk>/', IssueDetailView.as_view(), name='detail_issue'),
    path('list_issue/', IssueListView.as_view(), name='list_issue'),
    path('update/<int:pk>/', IssueUpdateView.as_view(), name='update_issue'),
    path('delete/<int:pk>/', IssueDeleteView.as_view(), name='delete_issue'),
    #path( path('detail/<int:pk>/', IssueDetailView.as_view(), name='detail_issue'),


    path('categories/', CategoriesView.as_view(), name='create_categories'),
    path('types/', typesView.as_view(), name='create-types'),


    ]

proyecto_1/apps/registration/urls.py
from django.urls import path
from .views import LoginView ,RegistrationView

app_name="registration2"

urlpatterns = [
    path('login/',LoginView.as_view(),name='login'),
    path('register/',RegistrationView.as_view(),name='register'),
    
    ]

proyecto_1/proyecto_1/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('apps.registration.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('contacts/', include('apps.contact.urls')),
    path('issue/', include('apps.issue.urls')),
    path('', include('apps.core.urls')),
    
]

proyecto_1/apps/core/models.py
from django.db import models

# Create your models here.

proyecto_1/apps/core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView ,ListView
from apps.issue.models import IssueModel
import datetime
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
# Create your views here.


@method_decorator(login_required, name='dispatch')
class HomeViews(ListView):
    template_name = 'core/home.html'
    model= IssueModel
    context_object_name = 'issue'
    
    def get_queryset(self):

        today_date = datetime.datetime.now().date()
        day=15
        substration_day = datetime.timedelta(days=day)
        before = today_date -  substration_day

        queryset = {'issue_all': IssueModel.objects.all(), 
                    'issue_reminder': IssueModel.objects.all().filter(fecha__lte=before)}

        return queryset

    

    

proyecto_1/apps/core/templates/core/base.html
{% load static %}
<!DOCTYPE html5>
<html>
<head>
<meta charset="utf-8">
	<meta name="Author" content="Gabriel Gonzalez Rangel">
	<meta name="Description" content="">
	<meta name="keywords" content="">
	<title> {% block title %}{% endblock %} | FriolectTotalPlus</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximun-scale=1.0, minimun-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
	
</head>

<style>
    #comentariocliente,#instrucciones  {
        resize: none;
    }
</style>

<body>

		<!-- Navegación -->		
	<header>
	
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
			<div class="container">
				 
				<a href="{% url 'core:home-core' %}"><img src="{% static 'core/img/logohome.png' %}"width="210" height="35"></a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#MenuNavegacion" aria-expanded="false" arial-label="alternar Menu">
					<span class="navbar-toggler-icon"></span>
				</button>


			<div class="collapse navbar-collapse" id="MenuNavegacion">
		<ul class="navbar-nav mr-auto" >
			<li class="nav-item">
				<a class="nav-link" href="{% url 'issue:create_issue' %}">Agregar pendiente</a></li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'issue:list_issue' %}">Lista de Pendiente</a></li>
			<li class="nav-item">
				<a  class="nav-link" href="{% url 'contact:create-contact' %}">Agregar Cliente</a></li>
			<li class="nav-item">	
				<a  class="nav-link" href="{% url 'contact:contacts' %}">Clientes</a></li>
			<li class="nav-item">

				{%if not request.user.is_authenticated %}
				<a  class="nav-link" href="{% url 'registration:login' %}">Iniciar Sesion</a></li>
				{%else%}
				<a  class="nav-link" href="{% url 'registration:logout' %}">Cerrar Sesión</a></li>
				{%endif%}
		</ul>
		
		
			</div>	
    </header>
    
	{% block content %}    
	{% endblock %}

    
</body>
    <footer>

		<meta name="viewport" content="width=device-width, initial-scale=1">
                        
                       
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
              
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" ></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" ></script>
        
    </footer>
    </html>

proyecto_1/apps/core/templates/core/home.html
<!-- tabla -->
{% extends "core/base.html"%}
{% block title %}Home{% endblock %}


{%block content%}

<mian class="container">
	<p class="h3 text-center">Pendientes</p>
	
	<div class="d-flex justify-content-center">
		<div class="col-8">
			{%if 'created_issue' in request.GET%}
                <div class="" role="">
					<p class="text-success">Pendiente Creado Correctamente. ir a <a href="{% url 'issue:list_issue' %}">Lista de Pendientes</a></p>
				</div>
				
                {%endif%}
			<table class="table table-hover">
				<thead class="thead-dark">
					<tr>
						<th>N°</th>
						<th>Cliente</th>
						<th>Fecha</th>
						<th>Hora</th>
						<th>Categoria</th>
						<th><a class="nav-link p-0" href="{% url 'issue:create_issue' %}">Agregar</a></th>
					</tr>
				</thead>

				{%for issue in issue.issue_all %}
				
				{% if issue.estado == "Abierto"%}
				
				<tbody>
				<tr>
					<td>{{issue.id}}</td>
					<td><a href="{% url 'issue:detail_issue' issue.id %}">{{issue.cliente}}</a></td>
					<td>{{issue.fecha}}</td>
					<td>{{issue.hora}}</td>
					<td>{{issue.categoria}}</td>
					<td></td>
				</tr>
				<tr>
				{% endif %}

				{% empty %}

				<tbody>
					<tr>
						<td> ---- </td>
						<td><a class="nav-link" href="{% url 'issue:create_issue' %}">Agregar</a></td>
						<td> ---- </td>
						<td> ---- </td>
						<td> ---- </td>
						<td> ---- </td>
					</tr>
					<tr>
				{%endfor%}
			</tbody>
			</table>
			</div>
		</div>
	</mian>


		
	
	<p class="h3 text-center">Cerrados</p>
<mian class="container">
<div class="d-flex justify-content-center">
<div class="col-8">
<table class="table table-hover">
	<thead class="thead-dark">
	<tr>
		<th>N°</th>
		<th>Cliente</th>
		<th>Fecha</th>
		<th>Hora</th>
		<th>Categoria</th>
		<th>Fecha de Cierre</th>
	</tr>
	</thead>
	<tbody>

		{%for issue in issue.issue_all %}
		{% if issue.estado == "Cerrado"%}
	<tbody>
	<tr>
		<td>{{issue.id}}</td>
		<td><a href="{% url 'issue:detail_issue' issue.id %}">{{issue.cliente}}</a></td>
		<td>{{issue.fecha}}</td>
		<td>{{issue.hora}}</td>
		<td>{{issue.categoria}}</td>
		<td>{{issue.updated}}</td>
	</tr>
	<tr>
		{% endif %}
		{%endfor%}
	</tbody>
</table>

</div>
</div>
</mian>



<!--                -->
				<p class="h3 text-center">Recordatorio </p>
			

<mian class="container">
	<div class="d-flex justify-content-center">
		<div class="col-8">
			
			<table class="table table-hover">
				<thead class="thead-dark">
				<tr>
					<th>N°</th>
					<th>Cliente</th>
					<th>Fecha Programada</th>
					<th>Hora</th>
					<th>Categoria</th>
				</tr>
				</thead>
				<tbody>
					{%for issue in issue.issue_reminder %}
					<tbody>
					<tr>
						<td>{{issue.id}}</td>
						<td><a href="{% url 'issue:detail_issue' issue.id %}">{{issue.cliente}}</a></td>
						<td>{{issue.fecha}}</td>
						<td>{{issue.hora}}</td>
						<td>{{issue.categoria}}</td>
					</tr>
					<tr>
					{%endfor%}
					
				</tbody>
			</table>
				</div>
	</div>
</mian>
	</div>
	</div>
	</div>

	{%endblock%}