proyecto_1/apps/contact/urls.py
from django.urls import path
from .views import CreateContact, ListViewContact,Contact,UpdateContact,DeleteViewContact

app_name="contact"

urlpatterns = [
    path('',ListViewContact.as_view(),name="contacts"),
    path('create/',CreateContact.as_view(),name='create-contact' ),
    path('update/<int:pk>/',UpdateContact.as_view(), name='update-contact' ),
    path('contact/<int:pk>/',Contact.as_view(),name="detail-contact" ),
    path('delete/<int:pk>/',DeleteViewContact.as_view(),name="delete-contact" ),
   # path('/contacts/delete', ),
    
]

proyecto_1/apps/core/urls.py
from django.urls import path, include
from .views import HomeViews 

app_name="core"

urlpatterns = [
    path('', HomeViews.as_view(),name='home-core' ),
    
    
    #path('home/', .as_view(),name='' )
]

proyecto_1/apps/issue/urls.py
from django.urls import path 
from .views import IssueCreateView, CategoriesView , typesView,IssueDetailView, IssueListView ,IssueUpdateView, IssueDeleteView

app_name="issue"

urlpatterns = [
    path('create/', IssueCreateView.as_view(), name='create_issue'),
    path('detail/<int:pk>/', IssueDetailView.as_view(), name='detail_issue'),
    path('list_issue/', IssueListView.as_view(), name='list_issue'),
    path('update/<int:pk>/', IssueUpdateView.as_view(), name='update_issue'),
    path('delete/<int:pk>/', IssueDeleteView.as_view(), name='delete_issue'),
    #path( path('detail/<int:pk>/', IssueDetailView.as_view(), name='detail_issue'),


    path('categories/', CategoriesView.as_view(), name='create_categories'),
    path('types/', typesView.as_view(), name='create-types'),


    ]

proyecto_1/proyecto_1/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('apps.registration.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('contacts/', include('apps.contact.urls')),
    path('issue/', include('apps.issue.urls')),
    path('', include('apps.core.urls')),
    
]

proyecto_1/apps/issue/models.py
from django.db import models
from apps.contact.models import ContactsModels
from datetime import datetime
from django import forms


STATUS = (('Abierto','Abierto'),
            ('Cerrado','Cerrado'),)
# Create your models here.

class CategoriesModels(models.Model):
    nombre = models.CharField(max_length=255 , unique=True )
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)


    def __str__(self):
        return self.nombre


class TypesModels(models.Model):
    nombre = models.CharField(max_length=255 , unique=True )
    categoria = models.ForeignKey(CategoriesModels,on_delete=models.CASCADE, null=False , blank=False)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def __str__(self):
        return self.nombre

class IssueModel(models.Model):

    cliente = models.ForeignKey(ContactsModels , on_delete=models.CASCADE,
                                                    null=False, blank=False)
    ubicacion = models.CharField(max_length=255)
    fecha = models.DateField()
    hora =models.TimeField()
    categoria = models.ForeignKey(CategoriesModels,on_delete=models.CASCADE,
                                                 null=False, blank=False)
    tipo = models.ForeignKey(TypesModels,on_delete=models.CASCADE,
                                        null=False, blank=False)
    instrucciones = models.TextField(blank=True,null=True)

    STATUS = (('Abierto','Abierto'),
                ('Cerrado','Cerrado'),

    )
    MOD_WORK = (('F','Full'),
              ('M','Mitad'),
    
    )

    estado = models.CharField(max_length=13, choices=STATUS ,default='Abierto')

    #fecha_cierre = models.DateField()
    
    mod_work = models.CharField(max_length=10, choices=MOD_WORK ,default='Full')
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def clean(self):
    
        if not (self.fecha >= datetime.now().date()):
            
            raise forms.ValidationError({"fecha":"Este campo no puede ser menor a hoy"})
        
    class Meta:
        ordering=['fecha','hora']

    def __str__(self):
        return str(self.cliente)

proyecto_1/apps/issue/forms.py
from django import forms
from .models import CategoriesModels ,IssueModel ,TypesModels, STATUS
from apps.contact.models import ContactsModels


class IssueForms(forms.ModelForm):

    cliente = forms.ModelChoiceField(queryset=ContactsModels.objects.all(),empty_label=None,widget=forms.Select(attrs={"class":"form-control","name":"cliente",}))
    
    ubicacion = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control","name":"ubicacion","placeholder":"Ubicación",}))  

    fecha = forms.DateField(input_formats=['%Y-%m-%d'], widget=forms.DateInput(format=('%Y-%m-%d'),attrs={"class":"form-control","type":"date" }))

    hora = forms.TimeField(input_formats=['%H:%M'],widget=forms.TimeInput(format=('%H:%M'),attrs={"class":"form-control","type":"time", }))                                                                                               
    
    categoria = forms.ModelChoiceField(queryset=CategoriesModels.objects.all(),empty_label=None,widget=forms.Select(attrs={"class":"form-control","name":"categoria",}))                                                               
    
    tipo = forms.ModelChoiceField(queryset=TypesModels.objects.all(),empty_label=None,widget=forms.Select(attrs={"class":"form-control","name":"tipo",}))
    
    instrucciones = forms.CharField(required=False,widget=forms.Textarea(attrs={"class":"form-control","name":"instrucciones", "id":"instrucciones","placeholder":"Instrucciones","rows":"3",}))  



    class Meta:
        model = IssueModel
        fields = ['cliente','ubicacion','fecha','hora','categoria','tipo','instrucciones','estado']

       

class CategoryForms(forms.ModelForm):

    nombre = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control","name":"ubicacion","placeholder":"Nombre de Categoria",})) 

    class Meta:
        model = CategoriesModels
        fields = '__all__'


class TypeForms(forms.ModelForm):

    nombre = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control","name":"ubicacion","placeholder":"Nombre de tipo",})) 
    categoria = forms.ModelChoiceField(queryset=CategoriesModels.objects.all(),empty_label=None,widget=forms.Select(attrs={"class":"form-control","name":"Tipo",}))

    class Meta:
        model = TypesModels
        fields = '__all__'

proyecto_1/apps/issue/views.py
from django.shortcuts import render
from .forms import IssueForms
from django.views.generic import CreateView , UpdateView , DetailView , ListView ,DeleteView
from .models import IssueModel , CategoriesModels , TypesModels ,STATUS
from django.urls import reverse_lazy

from .forms import IssueForms ,CategoryForms, TypeForms
from django import forms
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required




# Create your views here.
@method_decorator(login_required, name='dispatch')
class IssueCreateView(CreateView):
    template_name = 'issue/create_issue.html'
    model  = IssueModel
    form_class = IssueForms

    def post(self, request, *args, **kwargs):
        self.object = None   
        return super().post(request, *args, **kwargs)


    def get_success_url(self):
        return reverse_lazy('core:home-core') + '?created_issue'

    def get_form(self,form_class=None):
        # modificar el wiget en tiempo real para no perder las validaciones por defecto 
        form = super(IssueCreateView, self).get_form()
        form.fields['estado'].widget = forms.Select(choices=STATUS,attrs={'placeholder':'Nombre de Usuario','class':'form-control'})
        return form



@method_decorator(login_required, name='dispatch')
class IssueDetailView(DetailView):
    template_name = 'issue/detail_issue.html'
    model  = IssueModel
    context_object_name="object"

@method_decorator(login_required, name='dispatch')    
class IssueListView(ListView):
    template_name = 'issue/list_issue.html'
    model  = IssueModel

@method_decorator(login_required, name='dispatch')
class IssueUpdateView(UpdateView):
    template_name = 'issue/update_issue.html'
    model  = IssueModel
    form_class = IssueForms

    def get_success_url(self):
        issueid=self.kwargs['pk']
        return reverse_lazy('issue:detail_issue',kwargs={'pk': issueid}) + '?update_issue'


@method_decorator(login_required, name='dispatch')
class CategoriesView(CreateView):
    template_name = 'issue/create_categories.html'
    form_class = CategoryForms
    model = CategoriesModels
    success_url = reverse_lazy('issue:create-types')

@method_decorator(login_required, name='dispatch')
class typesView(CreateView):

    template_name = 'issue/create_types.html'
    form_class = TypeForms
    model = TypesModels
    success_url = reverse_lazy('issue:create_issue')


@method_decorator(login_required, name='dispatch')
class IssueDeleteView(DeleteView):
    model = IssueModel
    template_name = 'issue/delete_issue.html'




    def get_success_url(self):
        return reverse_lazy('core:home-core') + '?delete_issue'

proyecto_1/apps/issue/templates/issue/create_categories.html
{% extends "core/base.html"%}

{% block title %}Crear Categoria{% endblock %}


{%block content%}
<div class="container">

    <h1>Crea una Categoria</h1>

    <form  method="post">{% csrf_token %}
        <div class="col-md-12">
            <div class="form-group">
                {{form.errors}}  
                {{form.nombre}}  


            </div>
        </div>

        <div class="col-md-12">
            <div class="form-group">

        <button class="btn btn-primary" type="submit">Crear Categoria </button>


    </div>
</div>
    </form>

</div>

{% endblock %}

proyecto_1/apps/issue/templates/issue/create_issue.html
{% extends "core/base.html"%}
{% block title %}Create-Issue{% endblock %}


{%block content%}

<div class="container">
    <p class="h2 text-center p-3">AGREGAR PENDIENTE</p>
    <br>

    <div class="row">
        <div class="col-md-6">
            <div class="col-md-12">
                {%if 'created_issue' in request.GET%}
                <div class="alert alert-success" role="alert">
                    <p>Pendiente Creado Correctamente. ir a <a href="{% url 'issue:list_issue' %}">Lista de Pendientes</a> </p>
                </div>
                {%endif%}
            </div>

        <form action="" method="post" class="form-horizontal">  {% csrf_token %}
   
            <div class="col-md-12">
            <div class="form-group">
                <label for="name"></label>
                {{form.cliente.errors}}
                {{form.cliente}}
                
            </div>
            </div>
            <p class="font-italic" >Agregar nuvo Contacto <a href="{%url 'contact:create-contact'%}"> Aqui </a></p>    
    <hr>
            <div class="col-md-12">
                <div class="form-group">
                    <label for="ubication"></label>
                    {{form.ubicacion.errors}}
                    {{form.ubicacion}}
                </div>
            </div>
    <hr>
            <div class="col-md-12">
                <div class="form-group  ">
                    <label for="date">Fecha</label>
                    {{form.fecha.errors}}
                    {{form.fecha}}
                </div>
            </div>
    <hr>
            <div class="col-md-12">
                <div class="form-group">
                    <label for="hour">Hora </label>
                    {{form.hora.errors}}
                    {{form.hora}}
                    
                </div>
            </div>  
    <hr>  
            <div class="col-md-12">
                <div class="form-group">
                    <label for="Categorie">Categoria</label>
                    {{form.categoria.errors}}
            
                    {{form.categoria}}
                
                  </div>  
            
                </div>
                <div class="">
                    <p class="font-italic">Crear Categoria             <a href="{% url 'issue:create_categories' %}" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-plus"></span> </a></p>
            </div>                                                                
    <hr>   
            <div class="col-md-12">
                <div class="form-group">
                <label for="Tipe">Tipo </label>
                {{form.tipo.errors}}
                {{form.tipo}}
                </div>
            </div>
    <hr>
            <div class="col-md-12">
                <div class="form-group">
                    {{form.instrucciones.errors}}
                    {{form.instrucciones}}
               </div>
            </div>

            <div class="col-md-12">
                <div class="form-group">
                    {{form.estado.errors}}
                    {{form.estado}}
               </div>
            </div>

            <button class="btn btn-success float-left" type="submit">agregar</button>
                    
            <a class="btn btn-primary float-right" role="button" href="{%url 'core:home-core' %}">Salir</a>
        </form>
    </div>

    <div class="col-md-6">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d222605.46360202576!2d-58.53621592285078!3d-34.629607111842105!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95bcca3b4ef90cbd%3A0xa0b3812e88e88e87!2sBuenos+Aires%2C+CABA!5e0!3m2!1ses!2sar!4v1564298244476!5m2!1ses!2sar" width="540" height="270" frameborder="0" style="border:0" allowfullscreen></iframe>    
    </div>

            
    </div>

</div>

    
{% endblock %}

proyecto_1/apps/issue/templates/issue/create_types.html
{% extends "core/base.html"%}

{% block title %}Crear Categoria{% endblock %}


{%block content%}
<div class="container">


    {%if 'created-categorie' in request.GET%}

    <p>Categoria creada exitosa </p>

    {%endif%}
 
    <h1>Crea una Tipo</h1>

    <form  method="post">{% csrf_token %}
        <div class="col-md-12">
            <div class="form-group">
                {{form.errors}}  
                {{form.nombre}}  
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                {{form.errors}}  
                {{form.categoria}}  
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">

        <button class="btn btn-primary" type="submit">Crear tipo </button>
    </div>
</div>

    </form>

</div>

{% endblock %}
   

proyecto_1/apps/issue/templates/issue/delete_issue.html
{% extends "core/base.html"%}

{% block title %}Lista de Pendientes{% endblock %}


{%block content%}

<div class="container">

    
    
   


    <form class="" action="" method="post">{% csrf_token %}

        <div class="mt-5 md-5"> 
            <h3>Desea eliminar el Pendiente N° : {{ object.id }} </h3>
        </div>
        <div class="row mt-4">
            <div class="col-md-12">
                <p class="h4">Estado del Pendiente :  <b>{{object.estado}}</b></p>
            </div>
        </div>
       
    <div class="row mt-1">
        <div class="col-md-12">
            <div class="form-group">	
                <label  class ="h5" for="cliente">Cliente</label>	
                <input class="form-control" id="cliente"type="text" name="name"  value="{{object.cliente}}" readonly>
            </div>
        </div>
    </div>
    <div class="row mt-1">
        <div class="col-md-12">
            <div class="form-group">
                <label  class ="h5" for="ubicacion">Ubicación</label>		
                <input class="form-control" id="ubicacion" type="text" name="name"  value="{{object.ubicacion}}" readonly>
            </div>
        </div>
    </div>
    <div class="row mt-1">
        <div class="col-md-12">
            <div class="form-group">
                <label  class ="h5" for="cliente">Fecha</label>		
                <input class="form-control"  id="Fecha" type="text" name="name"  value="{{object.fecha}}" readonly>
            </div>
        </div>
    </div>
    <div class="row mt-1">
        <div class="col-md-12">
            <div class="form-group">	
                <label  class ="h5" for="Hora">Hora</label>		
                <input class="form-control"  id="Hora" type="text" name="name"  value="{{object.hora}}" readonly>
            </div>
        </div>
    </div>
    <div class="row mt-1">
        <div class="col-md-12">
            <div class="form-group">
                <label  class ="h5" for="Tipo">Categoria / Tipo</label>		
                <input class="form-control" id="Tipo" type="text" name="name"  value="{{object.categoria}} / {{object.tipo}} " readonly>
            </div>
        </div>
    </div>
    
    <div class="row mt-1">
        <div class="col-md-12">
            <div class="form-group">
                <label  class ="h5" for="instruciones">Instruciones</label>			
                    <textarea class="form-control" id="instruciones" rows="3" readonly></textarea>
            </div>
        </div>
    </div>

    

        <button class="btn btn-danger " type="submit">Eliminar </button>

        <a class="btn btn-primary " href="{% url 'contact:update-contact' object.id %}"> Cancelar </a>

    </form>
    
</div>

{%endblock%}

</html>

proyecto_1/apps/issue/templates/issue/detail_issue.html
{% extends "core/base.html"%}
{% block title %}detalle-Issue{% endblock %}


{%block content%}

    
    <div class="container">

        <div class="row">
            <div>
        <p class="h2">DETALLE PENDIENTE</p>
            </div>
        </div>
        <br>
        {%if "update_issue" in request.GET %}
        <div class="alert alert-success" role="alert">
            <p >Se ha Modificado  Correctamente</p>
        </div>
            {% endif %}
        <div class="row">
            
        
            <div class="col-md-6">
                <p class="h4 ml-3">Pendiente N° {{object.id}}</p>
                <div class="col-md-12">
    <div class="control-label form-group">
        <label for="name">Cliente</label>
        <input class="form-control" type="text" name="name" value="{{object.cliente}}" readonly>
        </div>

</div>
<hr>

<div class="col-md-12">
        <div class="form-group">
        <label for="ubication">Ubicación</label>
        <input class="form-control" type="text" name="name" value="{{object.ubicacion}}" readonly>
        </div>

</div>
<hr>
<div class="col-md-12">
    <div class="form-group  ">
        <label for="date">Fecha</label>
        <input class="form-control" name="name" value="{{object.fecha}}" readonly>
    </div>

</div>
<hr>
<div class="col-md-12">
    <div class="form-group">
        <label for="hour">Hora </label>
        <input class="form-control" type="time" name="name" value="{{object.hora}}" readonly>
        
    </div>
</div>  
<hr>  
<div class="col-md-12">
    <div class="form-group">
    <label for="Categorie">Categoria</label>
    <input class="form-control" type="text" name="name" value="{{object.categoria}}" readonly>
    </div>
</div>  
<hr>

<div class="col-md-12">
    <div class="form-group">
    <label for="Tipe">Tipo </label>
    <input class="form-control" type="text" name="name" value="{{object.tipo}}" readonly>
    </div>
</div>
<hr>
<div class="col-md-12">
    <div class="form-group">
        <textarea class="form-control" name="instrucciones" rows="3" readonly>{{object.instrucciones}}</textarea>
   </div>
</div>


<div class="col-md-12">
    <div class="form-group">
        <p class="font-italic"> - F. Creación: {{object.created}}</p>
</div>
</div>

<div class="col-md-12">
    <div class="form-group">
        <p class="font-italic"> - F. Ultima actualización : {{object.updated}}</p>
    </div>
    
    </div>
    <hr>
    <div class="col-md-12 ">
    <a class="btn btn-Primary  btn-lg btn-block " href="{% url 'core:home-core' %}">Cancelar</a>
</div>

</div>
<div class="col-md-6">
    <div class="row p-4">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d222605.46360202576!2d-58.53621592285078!3d-34.629607111842105!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95bcca3b4ef90cbd%3A0xa0b3812e88e88e87!2sBuenos+Aires%2C+CABA!5e0!3m2!1ses!2sar!4v1564298244476!5m2!1ses!2sar" width="540" height="270" frameborder="0" style="border:0" allowfullscreen></iframe>   
    </div>


<div class="row mt-3 md-3">
<a class="btn btn-Primary btn-lg btn-block " href="{% url 'issue:update_issue' object.id %}">Editar</a>
</div>

<div class="row mt-3 md-3">
<a class="btn btn-Primary  btn-lg btn-block "  href="{% url 'issue:delete_issue' object.id %}">Eliminar</a>
</div>



</div>
    
   

    </div>
</div>
    

    
    {% endblock %}
</div>

</div>

proyecto_1/apps/issue/templates/issue/list_contact.html
{% extends "core/base.html"%}
{% block title %}Create-client{% endblock %}

{%block content%}


	<div class="container">
	
	
	<p class="h3 text-center p-3">Clientes</p>
	
	<div class="d-flex justify-content-center">
		<div class="col-8">
			{%if 'delete-client' in request.GET%}

    <p>El cliente se a eliminado  </p>

	{%endif%}
			<table class="table table-hover">
				<thead class="thead-dark">
					<tr>
						<th> ID Cliente</th>
						<th>Nombre</th>
						<th>Telefonos</th>
						<th><a  class="btn btn-primary btn-sm" href="{% url 'contact:create-contact' %}">Agregar </a></th>
						
					</tr>
				</thead>
				 {% for contact in object_list %}
				<tr>
					<td>{{contact.id}}</td>
                <td>{{contact.nombre}}</td>
                <td>{{contact.telefono}}/{{contact.s_telefono}}</td>
                <td><a href="{% url 'contact:detail-contact' contact.id %}">Ver</a></td>	
				</tr>
				
				{% endfor %}

			</table>
			</div>
		</div>
	</div>
		{% endblock %}


		

proyecto_1/apps/issue/templates/issue/list_issue.html
{% extends "core/base.html"%}
{% block title %}Pendientes {% endblock %}

{%block content%}


    {%if '?delete_issue' in request.GET%}

    <p>El Pendiente se a eliminado  </p>

    {%endif%}



    <div class="container">
	
	
        <p class="h3 text-center p-3">Lista De Pendientes</p>
        
        <div class="d-flex justify-content-center">
            <div class="col-10">

                <table class="table table-hover">
                    <thead class="thead-dark">
                        <tr>
                            <th> N°</th>
                            <th>Cliente</th>
                            <th>Ubicacion</th>
                            <th>Fecha</th>
                            <th>Hora</th>
                            <th>Categoria</th>
                            <th>Estado</th>
                            <th></th>
                        </tr>
                    </thead>

                    {% for issue in object_list %}
                    <tr>
                        <td>{{issue.id}}</td>
                        <td>{{issue.cliente}}</td>
                        <td>{{issue.ubicacion}}</td>
                        <td>{{issue.fecha}}</td>
                        <td>{{issue.hora}}</td>
                        <td>{{issue.categoria}}</td>
                        <td>{{issue.estado}}</td>
                        
                        <td><a href="{% url 'issue:detail_issue' issue.id %}">Ver</a></td>
    
                    </tr>
                    {% endfor %}
                </tbody>
                </table>
                </div>
            </div>
        </div>
            {% endblock %}

proyecto_1/apps/issue/templates/issue/update_issue.html
{% extends "core/base.html"%}
{% block title %}Edit-Issue{% endblock %}


{%block content%}
    
    {%if 'created_issue' in request.GET%}
    
    <p>Pendiente Creado Correctamente. ir a <a href="{% url 'issue:list_issue' %}">Lista de Pendientes</a> </p>

    {%endif%}
  
<form method="post"> {% csrf_token %}

<div class="container">

    <p class="h2 text-center p-3">Editar PENDIENTE</p>
    <br>
    <div class="row">
    
        <div class="col-md-6">
    
            <div class="col-md-12">
                {%if 'created_issue' in request.GET%}
    
                <p>Pendiente Creado Correctamente. ir a <a href="{% url 'issue:list_issue' %}">Lista de Pendientes</a> </p>
            
                {%endif%}
                
                <form class="form-horizontal" action="">
                    <div class="control-label form-group">
                    <label for="name"></label>
                    {{form.cliente.errors}}
                    {{form.cliente}}
                    </div>
            
            </div>
    <hr>
    
            <div class="col-md-12">
                    <div class="form-group">
                    <label for="ubication"></label>
                    {{form.ubicacion.errors}}
                    {{form.ubicacion}}
                    </div>
            
            </div>
    <hr>
            <div class="col-md-12">
                <div class="form-group  ">
                    <label for="date">Fecha</label>
                    {{form.fecha.errors}}
                    {{form.fecha}}
                </div>
            
            </div>
    <hr>
            <div class="col-md-12">
                <div class="form-group">
                    <label for="hour">Hora </label>
                    {{form.hora.errors}}
                    {{form.hora}}
                    
                </div>
            </div>  
    <hr>  
            <div class="col-md-12">
                <div class="form-group">
                <label for="Categorie">Categoria</label>
                {{form.categoria.errors}}
                {{form.categoria}}
                </div>
            </div>  
    <hr>
        
            <div class="col-md-12">
                <div class="form-group">
                <label for="Tipe">Tipo </label>
                {{form.tipo.errors}}
                {{form.tipo}}
                </div>
            </div>
    <hr>
            <div class="col-md-12">
                <div class="form-group">
                    {{form.instrucciones}}
               </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    {{form.estado}}
               </div>
            </div>

                <button class="btn btn-success float-left" type="submit">Editar</button>
                    
                
            <a class="btn btn-primary float-right" role="button" href="{%url 'core:home-core' %}">Salir</a>
    </div>
    </form>

    
   
    
    <div class="col-md-6">
        <div class="row p-4">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d222605.46360202576!2d-58.53621592285078!3d-34.629607111842105!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95bcca3b4ef90cbd%3A0xa0b3812e88e88e87!2sBuenos+Aires%2C+CABA!5e0!3m2!1ses!2sar!4v1564298244476!5m2!1ses!2sar" width="540" height="270" frameborder="0" style="border:0" allowfullscreen></iframe>   
        </div>


    <div class="row mt-3 md-3">
        <a class="btn btn-Primary btn-lg btn-block "  href="">Cerrar Pendiente</a>
    </div>

</div>
</div>
    
{% endblock %}