proyecto_1/apps/contact/urls.py
from django.urls import path
from .views import CreateContact, ListViewContact,Contact,UpdateContact,DeleteViewContact

app_name="contact"

urlpatterns = [
    path('',ListViewContact.as_view(),name="contacts"),
    path('create/',CreateContact.as_view(),name='create-contact' ),
    path('update/<int:pk>/',UpdateContact.as_view(), name='update-contact' ),
    path('contact/<int:pk>/',Contact.as_view(),name="detail-contact" ),
    path('delete/<int:pk>/',DeleteViewContact.as_view(),name="delete-contact" ),
   # path('/contacts/delete', ),
    
]

proyecto_1/apps/core/urls.py
from django.urls import path, include
from .views import HomeViews 

app_name="core"

urlpatterns = [
    path('', HomeViews.as_view(),name='home-core' ),
    
    
    #path('home/', .as_view(),name='' )
]

proyecto_1/apps/issue/urls.py
from django.urls import path 
from .views import IssueCreateView, CategoriesView , typesView,IssueDetailView, IssueListView ,IssueUpdateView, IssueDeleteView

app_name="issue"

urlpatterns = [
    path('create/', IssueCreateView.as_view(), name='create_issue'),
    path('detail/<int:pk>/', IssueDetailView.as_view(), name='detail_issue'),
    path('list_issue/', IssueListView.as_view(), name='list_issue'),
    path('update/<int:pk>/', IssueUpdateView.as_view(), name='update_issue'),
    path('delete/<int:pk>/', IssueDeleteView.as_view(), name='delete_issue'),
    #path( path('detail/<int:pk>/', IssueDetailView.as_view(), name='detail_issue'),


    path('categories/', CategoriesView.as_view(), name='create_categories'),
    path('types/', typesView.as_view(), name='create-types'),


    ]

proyecto_1/proyecto_1/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('apps.registration.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('contacts/', include('apps.contact.urls')),
    path('issue/', include('apps.issue.urls')),
    path('', include('apps.core.urls')),
    
]

proyecto_1/apps/contact/models.py
from django.db import models

# Create your models here.


class ContactsModels(models.Model):

    nombre = models.CharField(max_length=254,unique=True)
    direccion =models.CharField(max_length=254)
    telefono =models.SlugField(max_length=50,unique=True,error_messages={'unique':"ya Existe  este numero de telefono."})
    s_telefono = models.SlugField(max_length=50,unique=True,error_messages={'unique':"ya Existe este numero de telefono."})
    mail = models.EmailField(max_length=255,unique=True,error_messages={'unique':"ya Existe ese Correo electronico."})
    comentario =models.TextField(blank=True,max_length=254 ,null=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)    

    def __str__(self):
        return str(self.nombre)

        #crear table de direccioon


        

proyecto_1/apps/contact/forms.py
from django import forms
from .models import ContactsModels

class ContactsFoms(forms.ModelForm):
    
    nombre = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control",
                                                           "name":"name",
                                                           "placeholder":"Nombre",
                                                           }))
    direccion = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control",
                                                           "name":"direct",
                                                           "placeholder":"Direccion",
                                                           }))
    telefono = forms.CharField(error_messages={"invalid":"ya Existe ese numero de telefono"},widget=forms.TextInput(attrs={"class":"form-control",
                                                           "name":"phone",
                                                           "placeholder":"Telefono",
                                                           }))
    s_telefono = forms.CharField(error_messages={"invalid":"ya Existe ese numero de telefono"},widget=forms.TextInput(attrs={"class":"form-control",
                                                           "name":"phone2",
                                                           "placeholder":"Segundo Telefono",
                                                           }))
    mail = forms.EmailField(widget=forms.TextInput(attrs={"class":"form-control",
                                                           "name":"mail",
                                                           "type":"email",
                                                           "placeholder":"Mail",
                                                           }))
    comentario = forms.CharField(required=False,widget=forms.Textarea(attrs={"class":"form-control textarea-autosize",
                                                           "name":"name",
                                                           "id":"comentariocliente",
                                                           "placeholder":"Comentario",
                                                           "rows":"3"
                                                           }))

    class Meta:
        model = ContactsModels
        fields = '__all__'

proyecto_1/apps/contact/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView , DeleteView,ListView,DetailView
from django import forms

from django.utils.decorators import method_decorator

from django.contrib.auth.decorators import login_required
#
from django.urls import reverse_lazy
from django import template
# Create your views here.
from .forms import ContactsFoms
from .models import ContactsModels
from apps.issue.models import IssueModel



@method_decorator(login_required, name='dispatch')
class CreateContact(CreateView):
    template_name = 'contact/create_contact.html'
    model = ContactsModels
    form_class = ContactsFoms

    def post(self, request, *args, **kwargs):
        self.object = None
        print(request.POST)
        return super().post(request, *args, **kwargs)


    def get_success_url(self):
        return reverse_lazy('contact:create-contact') + '?client_create'
    
@method_decorator(login_required, name='dispatch')
class UpdateContact(UpdateView):
    template_name = 'contact/update_contact.html'
    model = ContactsModels
    form_class = ContactsFoms


    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        contactid=self.kwargs['pk']
        return super().get(request, *args, **kwargs)


    


    def get_success_url(self):
           #Tengo que capturar el pk de la query y pasarlo a la funcion de return en success #
          contactid=self.kwargs['pk']
          return reverse_lazy('contact:detail-contact', kwargs={'pk': contactid}) + "?client_updated"

@method_decorator(login_required, name='dispatch')
class Contact(DetailView):
    model = ContactsModels
    template_name = 'contact/detail_contact.html'

    def get_context_data(self, *args, **kwargs):
        context = super(Contact, self).get_context_data(*args, **kwargs)
        id=self.kwargs['pk']
        context['issues'] =IssueModel.objects.filter(cliente_id=id)
        context['contacts'] =ContactsModels.objects.all()
        return context


@method_decorator(login_required, name='dispatch')
class DeleteViewContact(DeleteView):
    model = ContactsModels
    template_name = 'contact/delete_contact.html'
    

    def get_context_data(self, *args, **kwargs):
        context = super(DeleteViewContact, self).get_context_data(*args, **kwargs)
        context['contacts'] = ContactsModels.objects.all()
        id=self.kwargs['pk']
        context['issues'] =IssueModel.objects.filter(cliente_id=id)
        context['counts'] =IssueModel.objects.filter(cliente_id=id).count()
        return context

    def get_success_url(self):
        return reverse_lazy('contact:contacts') + '?delete-client'


@method_decorator(login_required, name='dispatch')
class ListViewContact(ListView):
    template_name = 'contact/list_contact.html'
    
    model = ContactsModels

proyecto_1/apps/contact/templates/contact/create_contact.html
{% extends "core/base.html"%}
{% block title %}Create-client{% endblock %}


{%block content%}


<div class="container">
	<div class="row">
		<div class="col-md-12">
		<p class="h2 text-left">AGREGAR CLIENTE</p>
		</div>
	</div>

	{%if "client_create" in request.GET %}
        <p>Se ha creado un nuevo Cliente ver en <a href="{% url 'contact:contacts' %}">Lista Clientes</a></p>
		{% endif %}

		<form class="form-horizontal" method="post" action="">{%csrf_token%}
		
			<div class="row">
			<div class="col-md-12">
				<div class="form-group">
					{{form.nombre.errors}}		
					{{form.nombre}}
				</div>
			</div>
		</div>
<hr>
		
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">
					{{form.direccion.errors}}				
					{{form.direccion}}
				</div>
			</div>
		</div>

<hr>
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">
					{{form.telefono.errors}}		
					{{form.telefono}}
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">
					{{form.s_telefono.errors}}		
					{{form.s_telefono}}
				</div>
			</div>
		</div>
<hr>
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">
					{{form.mail.errors}}			
					{{form.mail}}
				</div>
			</div>
		</div>
<hr>
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">
					{{form.comentario.errors}}		
					{{form.comentario}}
				</div>
			</div>
		</div>
<hr>		
				
					<input class="btn btn-primary" type="submit"value="Crear Nuevo">
				
			<a class="btn btn-primary float-right" role="button" href="{% url 'core:home-core'%}">Salir</a>
				

	</form>
</div>
</div>

{% endblock %}

proyecto_1/apps/contact/templates/contact/delete_contact.html
<!DOCTYPE html>
{% extends "core/base.html"%}
{% block title %}Delete-client{% endblock %}


{%block content%}
   

<div class="container" >
    
	<div class="mx-auto">
         
            <div class="row p-4"> 
        <h3 class="ml-4">Desea eliminar el usuario {{ object.nombre }} </h3>
         
        </div>

        <div class="col-md-12">
            <div class="form-group">
            <label for="">Nombre</label>
            <input class="form-control" type="text" name="name" value="{{ object.nombre }}" readonly>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
            <label for="">Direccion</label>
            <input class="form-control" type="text" name="name" value="{{ object.direccion }}" readonly>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
            <label for="">Telefono</label>
            <input class="form-control" type="text" name="name" value="{{ object.telefono }}" readonly>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
            <label for="">Mail</label>
            <input class="form-control" type="text" id name="name" value="{{ object.mail }}" readonly>
            </div>
        </div>

        <div class="col-md-12">
            <p class="font-italic" >los pendientes se eliminaran con el usuario.</p>
        </div>
        <div class="col-md-12">
            <label class="font-weight-bold" for="ubication">Cantidad de Pendientes :</label>
            <p class="h5 font-weight-bold">{{counts}}</p>
            <br>
           
        </div>

        <div class="col-12">

            <table class="table table-hover">
                <tbody>
                    {%for issue in issues%}
                <tr>
                    <tD> {{issue.id }}</tD>
                    <td>{{issue.cliente }} </td>
                    <td>{{issue.ubicacion}} </td>
                    <td>{{issue.fecha}} </td>
                    <td> {{issue.hora}} </td>
                    <td> {{issue.categoria}} </td>
                    <td> {{issue.estado}} </td>
                    <td><a href="{% url 'issue:detail_issue' issue.id %}">Ver</a> </td>

                    {%endfor%}
                </tr>
                </tbody>

            </table>
            
        </div>
    



        <div class="row p-4">
    <form action="" method="post">{% csrf_token %}

        <button class="btn btn-danger float-left ml-4" type="submit">Eliminar </button>

        <a class="btn btn-primary float-right ml-4" href=" {% url 'contact:update-contact' object.id %}"> Cancelar </a>

    </form>
    
</div>
</div>

</div>
    {% endblock %}
        

proyecto_1/apps/contact/templates/contact/detail_contact.html
{% extends "core/base.html"%}
{% block title %} Client{% endblock %}

{%block content%}

<div class="container">
	<div class="row">
		<div class="col-md-6 p-3">
		<p class="h2 text-left">Cliente {{object.nombre}}</p>
        </div>
        <div class="col-md-6 p-3">
         <a class="btn btn-danger float-right mr-3" role="button" href="{% url 'contact:delete-contact' object.id %}">Eliminar</a>
            
            </div>
	</div>

    
    {%if "client_updated" in request.GET %}

    <p>Se ha Modificado  Correctamente</p>

    {% endif %}
    

    
    <div class="container">
        <div class="row">
            <div class="col-md-12">
            <p class="h4 text-left"> N° {{object.id}} </p>
                <form class="form-horizontal" action="">
            </div>
        </div>
        
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">		
                        <input class="form-control" type="text" name="name" placeholder="nombre" value="{{object.nombre}}" readonly>
                    </div>
                </div>
            </div>
    <hr>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">		
                        <input class="form-control" type="text" name="direct" placeholder="Dirección"value="{{object.direccion}}"readonly >
                    </div>
                </div>
            </div>
    
    <hr>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">		
                        <input  class="form-control" type="text" name="phone" placeholder="Telefono" value="{{object.telefono}}"readonly>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">		
                        <input class="form-control" type="text" name="phone2" placeholder="Segundo Telefono" value="{{object.s_telefono}}" readonly>
                    </div>
                </div>
            </div>
    <hr>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">		
                        <input class="form-control" type="text" name="mail" placeholder="Correo Electronico" value="{{object.mail}}" readonly>
                    </div>
                </div>
            </div>
    <hr>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">		
                        <textarea class="form-control" id= "comentariocliente" placeholder="Comentario" rows="3" readonly>{{object.comentario}}</textarea >
                    </div>
                </div>

            
                    
                <a class="btn btn-primary float-right ml-4" role="button" href="{% url 'contact:update-contact' object.id %}">Editar</a>
    <hr>		
               
                <a class="btn btn-primary float-right mr-4" role="button" href="{% url 'core:home-core' %}">Salir</a>
        </form>
    </div>
</div>
 
    <hr>
        <div class="row">

                <div class="col-12">

                <table class="table table-hover">
                    <thead class="thead-dark">
                        <tr>
                            <th> N°</th>
                            <th>Cliente</th>
                            <th>Ubicacion</th>
                            <th>Fecha</th>
                            <th>Hora</th>
                            <th>Categoria</th>
                            <th>Estado</th>
                            <th></th>
                        </tr>
                    </thead>
                        {%for issue in issues%}
                    <tr>
                        <tD> {{issue.id }}</tD>
                        <td>{{issue.cliente }} </td>
                        <td>{{issue.ubicacion}} </td>
                        
                        <td>{{issue.fecha}} </td>
                        <td> {{issue.hora}} </td>
                        <td> {{issue.categoria}} </td>
                        <td> {{issue.estado}} </td>
                        {%endfor%}
                        
                    </tr>
                    </tbody>
                </table>
                
            </div>
        </div>
    </div>
    </div>


{% endblock %}

proyecto_1/apps/contact/templates/contact/list_contact.html
{% extends "core/base.html"%}
{% block title %}Create-client{% endblock %}

{%block content%}


	<div class="container">
	
	
	<p class="h3 text-center p-3">Clientes</p>
	
	<div class="d-flex justify-content-center">
		<div class="col-8">
			{%if 'delete-client' in request.GET%}

    <p>El cliente se a eliminado  </p>

	{%endif%}
			<table class="table table-hover">
				<thead class="thead-dark">
					<tr>
						<th> ID Cliente</th>
						<th>Nombre</th>
						<th>Telefonos</th>
						<th><a  class="btn btn-primary btn-sm" href="{% url 'contact:create-contact' %}">Agregar </a></th>
						
					</tr>
				</thead>
				 {% for contact in object_list %}
				<tr>
					<td>{{contact.id}}</td>
                <td>{{contact.nombre}}</td>
                <td>{{contact.telefono}}/{{contact.s_telefono}}</td>
                <td><a href="{% url 'contact:detail-contact' contact.id %}">Ver</a></td>	
				</tr>
				
				{% endfor %}

			</table>
			</div>
		</div>
	</div>
		{% endblock %}

proyecto_1/apps/contact/templates/contact/update_contact.html
{% extends "core/base.html"%}
{% block title %}Create-client{% endblock %}

{%block content%}

<div class="container">
	<div class="row">
		<div class="col-md-6 p-3">
		<p class="h2 text-left">Editar </p>
		</div>
		<div class="col-md-6 p-3">
            <a class="btn btn-danger float-right " role="button" href="{% url 'contact:delete-contact' object.id %}">Eliminar</a> 
        </div>
	</div>

	{%if "client_create" in request.GET %}
        <p>Se ha creado un nuevo Cliente ver en <a href="{% url 'contact:contacts' %}">Lista Clientes</a></p>
		{% endif %}

		<form class="form-horizontal" method="post" action="">{%csrf_token%}
		
			<div class="row">
			<div class="col-md-12">
				<div class="form-group">		
					{{form.nombre}}
				</div>
			</div>
		</div>
<hr>
		
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">		
					{{form.direccion}}
				</div>
			</div>
		</div>

<hr>
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">		
					{{form.telefono}}
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">		
					{{form.s_telefono}}
				</div>
			</div>
		</div>
<hr>
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">		
					{{form.mail}}
				</div>
			</div>
		</div>
<hr>
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">		
					{{form.comentario}}
				</div>
			</div>
		</div>
<hr>		
				
					<input class="btn btn-primary" type="submit"value="Finalizar">
				
			<a class="btn btn-primary float-right" role="button" href="{% url 'core:home-core'%}">Salir</a>
				

	</form>
</div>
</div>

{% endblock %}